### ISSUE TITLE
[Milestone] To do lists

### ISSUE THREAD

**Issue by JeonDohyeon** [dohyeon-ghworkspace/imitated-seed#3]
## 렌더러 오류 수정
- [ ] 삼중괄호 문제 해결 #2 gdl-blue#14
- [ ] 토론 댓글 문제 해결하기 gdl-blue#23
- [ ] 주석 파싱 고치기 gdl-blue#31
- [ ] gdl-blue#29

## 코드 가독성 해결
- [ ] #1 

## 기타 기능
- [ ] 파일 서버 추가 gdl-blue#15
- [ ] 이메일 인증 기능 gdl-blue#22

**Comment by JeonDohyeon** [comment]
### 렌더러 마일스톤
- [ ] 메가 마일스톤: 온갖 문법 짬뽕되어 있는 [이 문서](https://wiki.jdh5968.pe.kr/w/%EC%82%AC%EC%9A%A9%EC%9E%90%3Ajdh5968%2F%ED%85%8C%EC%8A%A4%ED%8A%B8)
  + Q. 이거 공개해도 되나요?
    * A. 전 상관 없습니다 - @JeonDohyeon

**Comment by aploga** [comment]
전 그래서 때려쳤슴다
